services:
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_started
    ports:
      - "5000:5000"
    volumes:
      - fastembed_cache:/tmp/fastembed_cache
    command: [ "sh", "/docker-entrypoint.sh", "gunicorn", "main:app" ]

  worker:
    build:
      context: ./backend
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_started
    volumes:
      - fastembed_cache:/tmp/fastembed_cache
    command: [ "arq", "worker.WorkerSettings" ]

  postgres:
    image: ${POSTGRES_IMAGE}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - "CMD"
        - "sh"
        - "-c"
        - "pg_isready -U ${POSTGRES_USER}"
      interval: 5s
      timeout: 3s
      retries: 40

  redis:
    image: ${REDIS_IMAGE}
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 40

  arq-ui:
    image: antonk0/arq-ui
    restart: always
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy

  ollama:
    image: ${OLLAMA_IMAGE}
    restart: always
    entrypoint: [ "/bin/sh", "/docker-entrypoint.sh" ]
    environment:
      ENTRYPOINT_MODE: ollama
      OLLAMA_BOOT_MODEL: qwen2.5:0.5b
      OLLAMA_HOST: "0.0.0.0"
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./backend/entrypoint.sh:/docker-entrypoint.sh:ro
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 5s
      timeout: 3s
      retries: 40

  qdrant:
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  ollama_data:
  redis_data:
  qdrant_data:
  fastembed_cache:
