"""Initial schema.

Revision ID: 96078f6fa6ee
Revises:
Create Date: 2026-02-05 02:55:33.196637

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "96078f6fa6ee"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the initial schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="Email address",
        ),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=False,
            comment="Hashed password",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Created at",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Updated at",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "llm_providers",
        sa.Column("user_id", sa.Integer(), nullable=False, comment="Owner user ID"),
        sa.Column(
            "name",
            sa.String(length=128),
            nullable=False,
            comment="Provider display name",
        ),
        sa.Column(
            "type",
            sa.Enum("OLLAMA", name="llmprovidertype"),
            nullable=False,
            comment="Provider type",
        ),
        sa.Column("api_key", sa.Text(), nullable=False, comment="Encrypted API key"),
        sa.Column(
            "base_url",
            sa.String(length=512),
            nullable=True,
            comment="Custom base URL for self-hosted providers",
        ),
        sa.Column(
            "is_default",
            sa.Boolean(),
            nullable=False,
            comment="Default provider for user",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflows",
        sa.Column("owner_id", sa.Integer(), nullable=False, comment="Owner user ID"),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Workflow name",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Created at",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Updated at",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "executions",
        sa.Column(
            "workflow_id",
            sa.Integer(),
            nullable=False,
            comment="Parent workflow ID",
        ),
        sa.Column(
            "status",
            sa.Enum("CREATED", "RUNNING", "SUCCESS", "FAILED", name="executionstatus"),
            nullable=False,
            comment="Execution status",
        ),
        sa.Column(
            "input_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Input data for execution",
        ),
        sa.Column(
            "output_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Output data from execution",
        ),
        sa.Column("error", sa.Text(), nullable=True, comment="Error message if failed"),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Execution start time",
        ),
        sa.Column(
            "finished_at",
            sa.DateTime(),
            nullable=True,
            comment="Execution end time",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nodes",
        sa.Column(
            "workflow_id",
            sa.Integer(),
            nullable=False,
            comment="Parent workflow ID",
        ),
        sa.Column(
            "type",
            sa.Enum("INPUT", "LLM", "OUTPUT", name="nodetype"),
            nullable=False,
            comment="Node type",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Node configuration data",
        ),
        sa.Column(
            "position_x",
            sa.Float(),
            nullable=False,
            comment="X position on canvas",
        ),
        sa.Column(
            "position_y",
            sa.Float(),
            nullable=False,
            comment="Y position on canvas",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edges",
        sa.Column(
            "workflow_id",
            sa.Integer(),
            nullable=False,
            comment="Parent workflow ID",
        ),
        sa.Column(
            "source_node_id",
            sa.Integer(),
            nullable=False,
            comment="Source node ID",
        ),
        sa.Column(
            "target_node_id",
            sa.Integer(),
            nullable=False,
            comment="Target node ID",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="ID"),
        sa.ForeignKeyConstraint(["source_node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the initial schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("edges")
    op.drop_table("nodes")
    op.drop_table("executions")
    op.drop_table("workflows")
    op.drop_table("llm_providers")
    op.drop_table("users")
    # ### end Alembic commands ###
